export { avifAJpg } from './tool/avifAJpg/entry';
export type { AvifAJpgLocaleContent } from './tool/avifAJpg/entry';
export { avifAPng } from './tool/avifAPng/entry';
export type { AvifAPngLocaleContent } from './tool/avifAPng/entry';
export { avifAWebp } from './tool/avifAWebp/entry';
export type { AvifAWebpLocaleContent } from './tool/avifAWebp/entry';
export { bmpAJpg } from './tool/bmpAJpg/entry';
export type { BmpAJpgLocaleContent } from './tool/bmpAJpg/entry';
export { bmpAPng } from './tool/bmpAPng/entry';
export type { BmpAPngLocaleContent } from './tool/bmpAPng/entry';
export { bmpAWebp } from './tool/bmpAWebp/entry';
export type { BmpAWebpLocaleContent } from './tool/bmpAWebp/entry';
export { gifAJpg } from './tool/gifAJpg/entry';
export type { GifAJpgLocaleContent } from './tool/gifAJpg/entry';
export { gifAPng } from './tool/gifAPng/entry';
export type { GifAPngLocaleContent } from './tool/gifAPng/entry';
export { gifAWebp } from './tool/gifAWebp/entry';
export type { GifAWebpLocaleContent } from './tool/gifAWebp/entry';
export { jpgAIco } from './tool/jpgAIco/entry';
export type { JpgAIcoLocaleContent } from './tool/jpgAIco/entry';
export { jpgAPng } from './tool/jpgAPng/entry';
export type { JpgAPngLocaleContent } from './tool/jpgAPng/entry';
export { jpgAWebp } from './tool/jpgAWebp/entry';
export type { JpgAWebpLocaleContent } from './tool/jpgAWebp/entry';
export { pngAIco } from './tool/pngAIco/entry';
export type { PngAIcoLocaleContent } from './tool/pngAIco/entry';
export { pngAJpg } from './tool/pngAJpg/entry';
export type { PngAJpgLocaleContent } from './tool/pngAJpg/entry';
export { pngAWebp } from './tool/pngAWebp/entry';
export type { PngAWebpLocaleContent } from './tool/pngAWebp/entry';
export { svgAJpg } from './tool/svgAJpg/entry';
export type { SvgAJpgLocaleContent } from './tool/svgAJpg/entry';
export { svgAPng } from './tool/svgAPng/entry';
export type { SvgAPngLocaleContent } from './tool/svgAPng/entry';
export { webpAIco } from './tool/webpAIco/entry';
export type { WebpAIcoLocaleContent } from './tool/webpAIco/entry';
export { webpAJpg } from './tool/webpAJpg/entry';
export type { WebpAJpgLocaleContent } from './tool/webpAJpg/entry';
export { webpAPng } from './tool/webpAPng/entry';
export type { WebpAPngLocaleContent } from './tool/webpAPng/entry';
export { imagenBase64 } from './tool/imagenBase64/entry';
export type { ImagenBase64LocaleContent } from './tool/imagenBase64/entry';
export { convertersCategory } from './category';
import { avifAJpg } from './tool/avifAJpg/entry';
import { avifAPng } from './tool/avifAPng/entry';
import { avifAWebp } from './tool/avifAWebp/entry';
import { bmpAJpg } from './tool/bmpAJpg/entry';
import { bmpAPng } from './tool/bmpAPng/entry';
import { bmpAWebp } from './tool/bmpAWebp/entry';
import { gifAJpg } from './tool/gifAJpg/entry';
import { gifAPng } from './tool/gifAPng/entry';
import { gifAWebp } from './tool/gifAWebp/entry';
import { jpgAIco } from './tool/jpgAIco/entry';
import { jpgAPng } from './tool/jpgAPng/entry';
import { jpgAWebp } from './tool/jpgAWebp/entry';
import { pngAIco } from './tool/pngAIco/entry';
import { pngAJpg } from './tool/pngAJpg/entry';
import { pngAWebp } from './tool/pngAWebp/entry';
import { svgAJpg } from './tool/svgAJpg/entry';
import { svgAPng } from './tool/svgAPng/entry';
import { webpAIco } from './tool/webpAIco/entry';
import { webpAJpg } from './tool/webpAJpg/entry';
import { webpAPng } from './tool/webpAPng/entry';
import { imagenBase64 } from './tool/imagenBase64/entry';
export const ALL_ENTRIES = [avifAJpg, avifAPng, avifAWebp, bmpAJpg, bmpAPng, bmpAWebp, gifAJpg, gifAPng, gifAWebp, imagenBase64, jpgAIco, jpgAPng, jpgAWebp, pngAIco, pngAJpg, pngAWebp, svgAJpg, svgAPng, webpAIco, webpAJpg, webpAPng];
